### PR TITLE
cleanup(examples)

### PR DESCRIPTION
**Pull request by vladdoster**
removed redundant logic, removed broken example typo from `printl` to `print`, made a simpler chained logic command and fixed odd formatting

I know they seem small, but we use pyslurm in production and its nice to show developers these and they use best conventions. Might as well fix them :)

### CODE REVIEW

**Comment by vladdoster** [comment]
Most of these are visual changes, but some of them are just good practices for python code

**Comment by giovtorres** [comment]
Thank you @vladdoster for cleaning this up! These examples definitely need some love. Would you mind running [pylint](https://www.pylint.org/) and [black](https://black.readthedocs.io/en/stable/) over the `examples/` directory? :pray: 

These tools would lint and format the files approriately.

**Comment by vladdoster** [comment]
@giovtorres, yes I can do that. Will push to upstream sometime today.

**Comment by vladdoster** [comment]
@giovtorres I updated the tests! The remaining errors are mostly in sjobs relating to line-too-long and I wasn't really sure how to fix it since I am not at work and don't have access to slurm right now to see how it would look.

Started out at ~3 and now pushing 10!

pic-selected-200201-1442-49

**Pull request merged**
