### PR TITLE
A number of fixes / enhancements

### PR DESCRIPTION
**Pull request by rfehren**
Please review and pull these commits.

### CODE REVIEW

**Comment by giovtorres** [comment]
Hi @rfehren, I think you need to merge the latest changes in master into your branch.  The current master is already bumped to 17.02.7 and there have been some changes to the Travis tests.

**Comment by rfehren** [comment]
>>>>> "G" == Giovanni Torres <notifications@github.com> writes:

Hi Giovanni,

    G> Hi @rfehren, I think you need to merge the latest changes in
    G> master into your branch. The current master is already bumped to
    G> 17.02.7 and there have been some changes to the Travis tests.

I merged master into my branch and pushed again. Can you work with this
or shall I make a new pull request?

**Comment by giovtorres** [comment]
Not sure why the latest test failed.  It says the script was not found, but the merge put the test scripts in place.  I wonder if rebasing your commits on top of an updated master would work better.  Do you want to give that a try?

**Comment by rfehren** [comment]
I generated a new PR generated against master.

**Pull request closed without merging**
