### PR TITLE
fix for python 3.6 where DLFCN was removed

### PR DESCRIPTION
**Pull request by veprbl**

### CODE REVIEW

**Comment by giovtorres** [comment]
Hi.  I would be more inclined to use `ctypes.RTLD_GLOBAL` instead of the `os.RTLD_GLOBAL` module.  This way, it would be supported from python 2.6 through 3.6.  This is what I have in the dev branch and hasn't made it yet into master.  Thoughts?

**Comment by veprbl** [comment]
When preparing this PR I was looking to minimize possible breakage. I now did a small test to see if additionally importing ctypes will take more time and didn't see any significant overhead, so, I guess, that ctypes can be very well used instead, especially if it has better compatibility.

**Comment by giovtorres** [comment]
I updated `__init__.py` in 9004364.  Give it a try.  Thanks.

**Comment by veprbl** [comment]
Thank you!

**Pull request closed without merging**
