### PR TITLE
Try running one test each on Python 3.5 and 3.6

### PR DESCRIPTION
**Pull request by cclauss**
Run those two tests in `allow_failures`mode.

https://travis-ci.org/PySlurm/pyslurm/pull_requests

### CODE REVIEW

**Comment by giovtorres** [comment]
The `.travis.yml` file is invalid and causes the build to fail.  For this to work, I think the `.travis.yml` file has to look something like this:

```
matrix:
  allow_failures:                                       
    - env: SLURM=17.02.7 CYTHON=0.26 CENTOS=7 PYTHON=3.5
    - env: SLURM=17.02.7 CYTHON=0.26 CENTOS=7 PYTHON=3.6
  include:
    - env: SLURM=17.02.7 CYTHON=0.26 CENTOS=7 PYTHON=3.5
    - env: SLURM=17.02.7 CYTHON=0.26 CENTOS=7 PYTHON=3.6
[...]
```

But why allow the failures?  We would want PySlurm to build on 3.5 and 3.6 with every commit.  We can try just adding one test each for 3.5 and 3.6 at the top and let's see if it builds on those two versions.  Do you want to update the PR?

**Comment by cclauss** [comment]
Thanks for the syntax help...  I was indeed struggling as you saw.  I will make the changes that you suggest.

**Comment by giovtorres** [comment]
I like the `python -m pip`... I forgot about that syntax.  The problem, however, is that Python 3.5 and 3.6 are not installed in the environment and will cause the builds to fail.  2b86b37 adds both versions from the IUS repo. 

Try merging this commit into your branch and then testing your PR again.  Thanks.

**Comment by cclauss** [comment]
https://travis-ci.org/PySlurm/pyslurm/jobs/275342225#L773-L774

> $ docker exec -e PYTHON=$PYTHON slurm-$SLURM /pyslurm/scripts/run_tests.sh
> /pyslurm/scripts/run_tests.sh: line 16: nosetests-3.6: command not found

**Comment by giovtorres** [comment]
abb615a fixes that error.  I went ahead and added the two env lines in .travis.yml to test Python 3.5 and 3.6.  Build passes now: https://travis-ci.org/PySlurm/pyslurm/builds/275508766.  I think we can close this PR.

**Comment by giovtorres** [comment]
Thanks @cclauss !

**Pull request closed without merging**
