### PR TITLE
slurm 24.05.X support

### PR DESCRIPTION
**Pull request by basvandervlies**
The code compiles and I can run our python slurm utils. For now I have disabled the `epilog|prolog' configs they have changed from `char *` to `char **`. Could not find a function for it. So that is still on the todo list

### CODE REVIEW

**Comment by tazend** [comment]
Hi @basvandervlies 

thank you for this. I will check it out soon in more detail, but looks good on a first quick glance.

**Comment by jvhaarst** [comment]
@basvandervlies: Thanks !

**Comment by fonsgithub** [comment]
Awesome @basvandervlies ! Thanks!
I've just installed your pr against our Slurm 24.05.1, and I can query Slurm just fine when I test.
I'll report here if anything weird shows up in our scripting

**Comment by tazend** [comment]
Sorry that it took so long to respond here. I made a new PR (#348) based on this one with some additional fixes, which is now merged into main. Thanks again @basvandervlies for working on it! :)

**Pull request closed without merging**
