### PR TITLE
Slurmdb API for 17.02.X

### PR DESCRIPTION
**Pull request by dinesh121991**
Slurmdb APIs and its Unit test (nosetest) script for PyslurmV17.02.X. In this PR, we are supporting Events, Cluster, Reservation, and Jobs slurmdb APIs.

### CODE REVIEW

**Comment by dinesh121991** [comment]
I see that slurmdb APIs and tests are failed for the build "https://travis-ci.org/PySlurm/pyslurm/jobs/376694386/config". 
Did you have a chance to find the reason, why it was failing with that config? 
How can we proceed to merge the perfect code? Really, I appreciate your response.

**Comment by dinesh121991** [comment]
docstring is included in the test scripts!!

**Comment by giovtorres** [comment]
Thanks @dinesh121991 for adding the docstrings.  I ran it locally and it failed 3 tests.
[pr-111.txt](https://github.com/PySlurm/pyslurm/files/2212020/pr-111.txt)

The `test_job_sacct` parsing has some of the values as keys.  Have a look.

**Comment by dinesh121991** [comment]
Thanks for pointing out. I gave patch for resolving problems. I could not reproduce scenario for slurmdb_job test. The output is scrampled, and not properly aligned in your environment. If you find the reason, then pls point it out.
Make sure reservation is created already before doing test.

sacct output in your log (pr-111.txt ).
                  "UID": "",
                  "MaxDiskRead": "1",
                  "Elapsed": "",
                  "ResvCPU": "root",
                  "Unknown": "",
                  "AveDiskRead": "",
                  "Account": "00:00:01",

**Pull request merged**
